[tools]
python = "3.13"
uv = "latest"
pre-commit = "latest"
ruff = "latest"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]

[hooks]
enter = "bash ./scripts/setup_project.sh"

[env]
UV_LINK_MODE = "copy"
